name: first workflow

on: push

jobs:
    First_job:
        runs-on: ubuntu_latest
        steps:
        - name: welcome messsage
          run: echo "hello! its my first job"

        - name: list files
          run: ls

        - name: Read file
          run: ls